### ISSUE TITLE
Sould futures in `Join` be dropped at completion of each?

### ISSUE THREAD

**Issue by dobasy** [yoshuawuyts/futures-concurrency#126]
Consider following code:
```rust
struct Foo(u64);

impl Drop for Foo {
    fn drop(&mut self) {
        println!("dropping {}", self.0)
    }
}

async fn do_something(a: Foo) -> Foo {
    sleep(Duration::from_millis(a.0 * 100)).await;
    println!("completed: {}", a.0);
    a
}

let a = do_something(Foo(1));
let b = do_something(Foo(2));
let c = do_something(Foo(3));
let d = do_something(Foo(4));

let (_x, _y, _z) = ((a, b).race(), c, d).join().await;
```

The output of this code is:
```
completed: 1
completed: 3
completed: 4
dropping 2
dropping 4
dropping 3
dropping 1
```

But if `tokio::join!`, `futures::join!`, or `futures::future::join3` is used instead of `Join::join`, the output will be:
```
completed: 1
dropping 2
completed: 3
completed: 4
dropping 4
dropping 3
dropping 1
```

**Comment by yoshuawuyts** [comment]
I see. It appears the drop ordering of this crate, and of other crates is different. I don't believe it's wrong though, and I don't think it would be wise for us to make assurances about drop ordering, especially since if we ever gain the ability to perform an `async Drop`, we will most likely want to execute a _concurrent `async Drop`_ - for which our current behavior would provide the most natural transition to.

Can you elaborate a bit more on why you require a specific drop ordering?

**Comment by dobasy** [comment]
My (simplified) use case is something like this:
```rust
async fn foo(tx: Sender<Value>) -> Result<(), String> {
    loop {
        let a = get_value_from_internet()
            .await
            .map_err(|_| "failed to get value from internet".into())?;
        if a.is_some_condition() {
            break;
        }
        if tx.send(a).await.is_err() {
            // bar should be returning Err
            return Ok(());
        }
    }

    Ok(())
}

async fn bar(rx: Receiver<Value>) -> Result<(), String> {
    // loop until corresponding tx is dropped
    while let Some(a) = rx.recv().await {
        write_to_disk(a)
            .await
            .map_err(|_| "failed to write to disk".into())?;
    }

    Ok(())
}

async fn run(cancel: impl Future<Output = ()>) -> Result<(), String> {
    let (tx, rx) = channel();

    let res = join!(
        (foo(tx), cancel.map(|_| Err("cancelled".into()))).race(),
        bar(rx),
    );

    match res {
        (Err(e), _) | (_, Err(e)) => Err(e),
        (Ok(_), Ok(_)) => Ok(()),
    }
}
```

In this case, changing to `Join::join` will cause a deadlock if `cancel` is completed first. I don't believe it's wrong either, but I was surprised to see that functions/macros with similar names behave differently.

**Comment by yoshuawuyts** [comment]
Yeah, this is a tricky one. In this example you're relying on the fact that an async channel sends a "close" message on drop to handle a signal on the other side. When dealing with concurrency the ordering between seemingly unrelated items shouldn't be assumed, so instead it would probably be better to rewrite your sending logic to send a message in both the success and failure cases - rather than dropping it.

This month the Async WG has been talking a bit more about async Drop, and I still believe we'll want to enable concurrent drop. Which means that at this time this is probably not a guarantee we should make.
