### ISSUE TITLE
Proposal: add `stream::Race`

### ISSUE THREAD

**Issue by dodomorandi** [yoshuawuyts/futures-concurrency#127]
I would like to propose an additional abstraction over streams: `race()`. This combinator is already available for `Future`s, but not for `Stream`s, and I think it is a valid building block to expose.

Take the following pseudo-code:
```rust
enum Msg {
    A(A),
    B(B),
    Stop,
}

let mut stream = (
    stream_a.map(Msg::A).chain(futures::stream::once(std::future::ready(Msg::Stop))),
    stream_b.map(Msg::B),
)
    .merge();

while let Some(msg) = stream.next().await {
    Msg::Stop => break,
    /* .. */
}
```

This pattern is extremely useful when one of the streams never terminates (`stream_b` in this case). However, it is not a _zero-cost abstraction_, because we need to keep an additional state and the _stream chain state machine_ in order to signal when one or more streams finished.

That's the reason I propose the new `stream::Race` abstraction: a _merge_ abstraction that stops on the first occurrence of `Poll::Ready(None)` instead of waiting for all the streams to terminate. This would also compose extremely well with other abstractions, i.e. you could _race_ two _merge_ streams in order to wait until completion the first of two _groups_ of streams.

Initially I wanted to propose a `RaceOk` abstraction as well, but now I think that the behavior could be a bit controversial and I would like to eventually discuss it in a separated context.

**Comment by yoshuawuyts** [comment]
Hey there, thanks for opening this! Unfortunately I don't believe this is a great match for this library, because as you've shown: defining the exact semantics you want is not that hard to do yourself. This library mostly contains concurrency *primitives*, which are hard to define yourself, and if they can: they're hard to make performant.

The fact that this requires calling `.chain` has an overhead of a single boolean + branch, which while not perfect, is unlikely to ever be an issue. In terms of ergonomics I hope that eventually the language will be able to smooth out the edges, so it would become possible to write something closer to this:

```rust
enum Msg {
    A(A),
    B(B),
    Stop,
}

let a = stream_a.map(Msg::A).chain(iter::once(async { Msg::Stop }));
let b = stream_b.map(Msg::B);
for await msg in (a, b).merge() {
    match msg {
        Msg::Stop => break,
        /* .. */
    }
}
```
