### ISSUE TITLE
Add tests for `no_std`

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/futures-concurrency#68]
The traits themselves are compatible with `no_std`, and the implementations for `array` and `tuple` should be compatible with `no_std` as well. But as we're adding optimizations, we're using things like `bitvec` to store metadata in, speeding things up - but that may require allocations.

We should author tests to ensure that the traits keep working on `no_std` environments, even as we add optimizations. On the implementation side we may even want to swap the implementations we provide for `no_std` environments if it turns out our more optimized approaches are incompatible - but I suspect we may not need to.

Either way: the first step is to author tests and put them in CI so we can ensure that `no_std` works going forward.

**Comment by yoshuawuyts** [comment]
Yes please!

**Comment by alexmoon** [comment]
FYI, I don't think #159 actually does anything. I believe the `#![no-std]` directive in the test file just prevents use of the standard library in the test, but the lib still pulls in std since it does not have a `#![no-std]` directive. I've opened #163 to add no-std support to the crate. On that branch you can run `cargo test --no-default-features` to run no-std tests.

**Comment by yoshuawuyts** [comment]
I believe #163 closes this. Thanks!
